server {
    listen 80;
    server_name grafana.anhtester.io.vn;

    location / {
        proxy_pass http://grafana;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}